name: Build CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          # for 18.x version, set following:
          # export NODE_OPTIONS=--openssl-legacy-provider
          node-version: 16.x
      - name: Use Rust stable
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: echo $PATH
      - run: >
          mkdir -p /opt/google/chrome/ \
            && cd /opt/google/chrome/ \
            && curl -L --proto '=https' --tlsv1.2 --output /tmp/chromedriver.zip \
            "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip" \
            && unzip /tmp/chromedriver.zip \
            && rm /tmp/chromedriver.zip \
            && ln -sf /opt/google/chrome/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver \
            && curl -L --proto '=https' --tlsv1.2 --output /tmp/chrome.zip \
            "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-linux64.zip" \
            && unzip /tmp/chrome.zip \
            && ln -sf /opt/google/chrome/chrome-linux64/chrome /usr/local/bin/google-chrome-stable \
            && ln -sf /usr/local/bin/google-chrome-stable /usr/local/bin/google-chrome \
            && rm /tmp/chrome.zip
      - run: cargo install wasm-pack
      - run: yarn
        # use the deploy env file
      - run: yarn test:wasm
      - run: cp .env.deploy .env
      - run: yarn check-format
      - run: yarn lint
      - run: yarn build --if-present
      - run: yarn test --watchAll=false
      # create package from latest for download
      - run: yarn package
      - uses: actions/upload-artifact@master
        with:
          name: build-artefact
          path: build
