# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  page:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-artefact
          path: build
      - name: Deploy as GH Page
        # You may pin to the exact commit or the version.
        # uses: Cecilapp/GitHub-Pages-deploy@f26df39a27b93cae2c6aac5e07fdc556e8770247
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A verified email.
          email: lucien@zuercher.io
          # Where static files are.
          build_dir: build
          # Which branch to push files.
          # branch: # optional
          # The custom domain name.
          # cname: # optional
          # `yes` in case of a Jekyll site.
          # jekyll: # optional, default is no
